import "./globals.css";
import type { Metadata } from "next";
import { Inter, Sansita, Adamina } from "next/font/google";
import { NextUiProvider } from "@/components/NextUiProvider";
import NavbarComponent from "@/components/Navbar";
import Footer from "@/components/Footer";
import GotoTopBtn from "@/components/GotoTopBtn";
const adamina = Adamina({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={adamina.className}>
        <NextUiProvider>
          <NavbarComponent />
          {children}
          <Footer />
        </NextUiProvider>
        <GotoTopBtn />
      </body>
    </html>
  );
}
